# Generated by Django 3.0.2 on 2020-07-14 19:00

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200714_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='term', verbose_name='slug')),
            ],
        ),
    ]
