# Generated by Django 3.0.2 on 2020-07-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, default='testimony/avatar.jpg', null=True, upload_to='testimony/')),
                ('message', models.TextField()),
                ('approved', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='assisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='email',
            field=models.EmailField(default='abc@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='assistancerequest',
            name='ticket_id',
            field=models.CharField(default='rtec', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
