# Generated by Django 4.2.3 on 2023-08-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_assistancerequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
